### ISSUE TITLE
Analyze Initial Ingestion Pipeline

### ISSUE THREAD

**Issue by datascienceclubUVU** [datascienceclubUVU/UVU-2022-2023#30]
I have uploaded the initial ingestion pipeline to the data-engineering branch on the repository. This pipeline works, though is quite slow. To help achieve performance requirements, please analyze this pipeline and research and implement changes to help optimize the overall performance of the pipeline.

**Comment by dwk601** [comment]
Thank you for providing the initial ingestion pipeline. I will definitely take a look at it and analyze the performance. I will research and implement changes to optimize the overall performance of the pipeline. I will keep you updated on my progress and let you know if I need any further information or assistance.

**Comment by dwk601** [comment]
I just push a commit about adding a caching to our pipeline. Can you check that?

**Comment by datascienceclubUVU** [comment]
added dictionary comprehension and created temp cs ingestion pipeline as we work out remote OLTP connection issues.
